# Introduction

***We use NumPy because:***

* **NumPy** provides powerful multi-dimensional array operations and mathematical functions, optimized for numerical computing. It's efficient for handling large arrays and performing fast computations.

In short, NumPy for numerical computing and efficient array operations.

***Why to use NumPy:-***

    • Fast
	• Provide efficient storage
	• Better ways of handling data for processing
	• Easy to learn
	• Use relatively less memory to store data


In [1]:
import numpy as np

 # List v/s Numpy - Time taken

***Numpy v\s List in Python***
* Faster to read less bytes of memory in numpy, list use more bytes to store same
  thing.
* no type checking when iterating through objects in numpy while list can have
  int, float, boolean etc etc..
* Numpy uses contiguous memory but list don't

### Time Taken by List

In [12]:
from time import process_time

In [13]:
python_list = [i for i in range(10000000)]
start_time = process_time()

python_list = [ i+5 for i in python_list]
end_time = process_time()

print(f"Time Taken by list: {end_time - start_time}")

Time Taken by list: 0.5625


In [14]:
np_array = np.array(i for i in range(10000000))
start_time = process_time()

np_array = np.array( i+5 for i in python_list)
end_time = process_time()

print(f"Time Taken by NP Array: {end_time - start_time}")

Time Taken by NP Array: 0.0


# Numpy Arrays Creation

In [15]:
# Array Creation Methods

In [16]:
np_array = np.array([1,2,3,4])
print(np_array)
print(type(np_array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [50]:
# creating 1-D array
np_array = np.array([4,5,6,7,9,0,8]) 
print(np_array)                                    # printing the array
print(f"Shape:- {np_array.shape}")                 # shape = row x column
print(f"Size:- {np_array.size}")                   # tells the size (no of objects)
print(f"Element at [1]:- {np_array[1]}")           # accessing a element at a particular index
print(f"Dta Type:- {np_array.dtype}")              # prints data type
np_array[2] = 23                                   # changing a element
print(np_array)

[4 5 6 7 9 0 8]
Shape:- (7,)
Size:- 7
Element at [1]:- 5
Dta Type:- int64
[ 4  5 23  7  9  0  8]


In [53]:
# creating 2-D array
td = np.array([(2,3,4,5),(6,7,8,9)])
print(td)                                    # printing the array
print(f"Shape:- {td.shape}")                 # shape = row x column
print(f"Size:- {td.size}")                   # tells the size (no of objects)
print(f"Dta Type:- {td.dtype}")              # prints data type

[[2 3 4 5]
 [6 7 8 9]]
Shape:- (2, 4)
Size:- 8
Dta Type:- int64


In [54]:
# creating 3-D array
myarr= np.array([[[1,2,3],[4,5,6]],
        [[6,3,8],[2,3,4]],
        [[9,8,7],[6,9,7]]], np.int32)
print(myarr)                                    # printing the array
print(f"Shape:- {myarr.shape}")                 # shape = row x column
print(f"Size:- {myarr.size}")                   # tells the size (no of objects)
print(f"Dta Type:- {myarr.dtype}")              # prints data type
# *The shape in above is as:-* 3 blocks, 2 rows, 3 cloumns

[[[1 2 3]
  [4 5 6]]

 [[6 3 8]
  [2 3 4]]

 [[9 8 7]
  [6 9 7]]]
Shape:- (3, 2, 3)
Size:- 18
Dta Type:- int32


In [19]:
# adding float values in array
fp = np.array([(2.9,3,4,5),(9,8,7,6)],dtype = float)
print(fp)
print(fp.shape)
print(fp.size)

[[2.9 3.  4.  5. ]
 [9.  8.  7.  6. ]]
(2, 4)
8


# Analysing np array

In [55]:
e = np.array([4,5,6,7,9,0,8]) 

In [56]:
# check its dimensions
print(e.shape)

(7,)


In [57]:
# number of elements
print(e.size)

7


In [58]:
# check it's data type
print(e.dtype)

int64


In [59]:
# number of dimensions
print(e.ndim)

1


In [63]:
e.nbytes  #total bytes or space consumed by array

56

# Initial placeholders in numpy arrays

In [20]:
# aka Intrinsic Numpy array creation objects 
# Creating Objects from methods defined in numpy 

In [21]:
# array with only 0's
z =np.zeros((3,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# array with only 1's
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# identity matrix
b = np.identity((5))
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
# array with random values between 0 and 1
c = np.random.random((3,4))
print(c)

[[0.22621645 0.15498165 0.5850533  0.9668065 ]
 [0.84187931 0.75262794 0.81537307 0.00839672]
 [0.7133254  0.80024657 0.60775496 0.29681595]]


In [25]:
emp= np.empty((4,2))
print(emp)
# makes an empty array of given dimensions with random values which can be changed using indices and can be assigned values accordingly

[[2.9 3. ]
 [4.  5. ]
 [9.  8. ]
 [7.  6. ]]


In [26]:
# array with random values specified by us
d = np.random.randint(1,20,(3,4))
print(d)

[[ 2 18 17  3]
 [15  8  6 13]
 [ 1  4  5  7]]


In [33]:
e = np.random.randint(1,20,(3,5))
print(e)

[[ 4 12 17  9  2]
 [12 10  1 17 17]
 [18 15 18  5  4]]


In [27]:
# it will give us no of values specified by us in a range
e = np.linspace(1,20,5) # it will give me 5 evenly spaced elements between 1 and 20 
print(e)

[ 1.    5.75 10.5  15.25 20.  ]


In [28]:
e_like = np.empty_like((e))
print(e)    # used for efficiency to copy an array and work on it 

[ 1.    5.75 10.5  15.25 20.  ]


In [29]:
# it will give us elements after specified step in a range
f = np.arange(1,20,6) #it will give me elements at a step size of 6 i.e the diffrence between 2 elements will be 6
print(f)

[ 1  7 13 19]


In [30]:
# array of a particular value
g = np.full((3,6),12)
print(g)

[[12 12 12 12 12 12]
 [12 12 12 12 12 12]
 [12 12 12 12 12 12]]


# Coverting other python structures to np array

In [31]:
list = [2,4,6,8,9]

q = np.asarray(list)
print(q)
print(type(q))

[2 4 6 8 9]
<class 'numpy.ndarray'>


In [32]:
tuple = (2,4,6,8,9)

w = np.asarray(tuple)
print(w)
print(type(w))

[2 4 6 8 9]
<class 'numpy.ndarray'>


# Mathematical operations on np arrays

In [38]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 +list2) # concatinate the 2 list not adds the ements in them

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [39]:
a1 = np.random.randint(1,10,(3,4))
a2 = np.random.randint(10,20,(3,4))
print(a1)
print(a2)

[[8 3 6 7]
 [1 6 8 9]
 [1 7 3 7]]
[[14 16 10 12]
 [10 11 14 16]
 [16 15 13 19]]


In [40]:
# There are 2 ways to do mathematical functions on an np array

In [41]:
# Method 1
print(f"Add: \n {a1 +a2}")
print(f"Sub: \n {a1 -a2}")
print(f"Multiply: \n {a1 *a2}")
print(f"Divide: \n {a1 /a2}")

Add: 
 [[22 19 16 19]
 [11 17 22 25]
 [17 22 16 26]]
Sub: 
 [[ -6 -13  -4  -5]
 [ -9  -5  -6  -7]
 [-15  -8 -10 -12]]
Multiply: 
 [[112  48  60  84]
 [ 10  66 112 144]
 [ 16 105  39 133]]
Divide: 
 [[0.57142857 0.1875     0.6        0.58333333]
 [0.1        0.54545455 0.57142857 0.5625    ]
 [0.0625     0.46666667 0.23076923 0.36842105]]


In [42]:
# Method 2 
print(f"Add: \n {np.add(a1,a2)}")
print(f"Sub: \n {np.subtract(a1,a2)}")
print(f"Multiply: \n {np.multiply(a1,a2)}")
print(f"Divide: \n {np.divide(a1,a2)}")

Add: 
 [[22 19 16 19]
 [11 17 22 25]
 [17 22 16 26]]
Sub: 
 [[ -6 -13  -4  -5]
 [ -9  -5  -6  -7]
 [-15  -8 -10 -12]]
Multiply: 
 [[112  48  60  84]
 [ 10  66 112 144]
 [ 16 105  39 133]]
Divide: 
 [[0.57142857 0.1875     0.6        0.58333333]
 [0.1        0.54545455 0.57142857 0.5625    ]
 [0.0625     0.46666667 0.23076923 0.36842105]]


# Array manipulation

*Some important methods are :-*
* **reshape**:- to change shape of a matrix from 1 to 2 d or 3 d array but the no of elements should remain same. For example suppose a 1 d array have 99 elements so we can make a 2 d array of (3,33) as product of them is also 99 or (3,3,11) as that is also 99
* **ravel**:- it is used to convert an array back into 1 d or a straight line.
* **transposing array**:- rows to columns and columns to rows

In [43]:
new = np.random.randint(1,10,(4,5))
print(new)
print(f"Shape: {new.shape}")

[[9 6 7 7 5]
 [6 8 6 1 2]
 [1 5 6 8 4]
 [9 2 4 9 8]]
Shape: (4, 5)


In [44]:
# transposing array i.e rows to columns and columns to rows
trans = np.transpose(new)
print(trans)
print(f"Shape: {trans.shape}")

[[9 6 1 9]
 [6 8 5 2]
 [7 6 6 4]
 [7 1 8 9]
 [5 2 4 8]]
Shape: (5, 4)


In [45]:
# Method 2
trans2 = new.T
print(trans2)
print(f"Shape: {trans2.shape}")

[[9 6 1 9]
 [6 8 5 2]
 [7 6 6 4]
 [7 1 8 9]
 [5 2 4 8]]
Shape: (5, 4)


In [46]:
# reshaping an array
# remember the size will remain the same 
rshape = new.reshape((2,10))
print(rshape)
print(f"Shape: {rshape.shape}")

[[9 6 7 7 5 6 8 6 1 2]
 [1 5 6 8 4 9 2 4 9 8]]
Shape: (2, 10)


In [48]:
rav= np.ravel(rshape)
print(rav)

[9 6 7 7 5 6 8 6 1 2 1 5 6 8 4 9 2 4 9 8]


In [61]:
new.flat  # gives an iterator to go through the array using for loop
for item in new.flat:
    print(item)

9
6
7
7
5
6
8
6
1
2
1
5
6
8
4
9
2
4
9
8


In [62]:
ex1 = np.array([1,2,4,6,2,9])
print("\n",ex1)

amax=ex1.argmax()
print("\n",amax)    # returns index of maximum value present

amin=ex1.argmin()
print("\n",amin)     # returns index of minimum value present

asort= np.sort(ex1)
print("\n",asort)    # returns array elements in sorted manner



 [1 2 4 6 2 9]

 5

 0

 [1 2 2 4 6 9]


# NumPy Axis

* 1-D arrays have 1 axis *(Axis 0)*
* 2-D arrays have 2 axis *(Axis 0 ,Axis 1)*
* 3-D arrays have 3 axis and so on ...
* Now suppose you want to represent a point on 2 d plane you will need 2 axis. Similarly to represent a 2 d array we will need 2 axis.
* **In 2 d array the Axis 0 is down the rows and Axis 1 is along the columns.**
* You performs various operations in NumPy for which you need axis.
* For example you may need to have sum of rows so you can sum values along Axis 0 for that.

In [64]:
ex = [[1,2,3],[4,5,6],[7,8,9]]
myarr= np.array(ex)
print(myarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
myarr.sum(axis=0)  # 1+4+7 , 2+5+8  , 3+6+9

array([12, 15, 18])

In [66]:
myarr.sum(axis=1)  # 1+2+3  , 4+5+6  , 7+8+9

array([ 6, 15, 24])